"""sprint_1_mfa_documents_memory_validation_hil

Revision ID: 9497e2cc63f8
Revises: 
Create Date: 2026-05-05 20:51:10.436540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9497e2cc63f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('documents', sa.Column('original_filename', sa.String(length=255), nullable=False))
    op.add_column('documents', sa.Column('mime_type', sa.String(length=64), nullable=False))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('status', sa.Enum('PENDING', 'PARSING', 'EXTRACTING', 'VALIDATING', 'REVIEW', 'APPROVED', 'REJECTED', 'ERROR', name='documentstatus'), nullable=False))
    op.add_column('documents', sa.Column('parse_level_reached', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('parse_result', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('extracted_entities', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('validation_result', sa.JSON(), nullable=True))
    op.add_column('documents', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.drop_constraint(op.f('documents_ao_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'])
    op.drop_column('documents', 'ao_id')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'vector_embedding')
    op.drop_column('documents', 'extra_metadata')
    op.add_column('users', sa.Column('mfa_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('mfa_backup_codes_hash', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_backup_codes_hash')
    op.drop_column('users', 'mfa_verified')
    op.add_column('documents', sa.Column('extra_metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('vector_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('extracted_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('ao_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ao_id_fkey'), 'documents', 'ao', ['ao_id'], ['id'])
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.alter_column('documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documents', 'error_message')
    op.drop_column('documents', 'processing_time_ms')
    op.drop_column('documents', 'validation_result')
    op.drop_column('documents', 'extracted_entities')
    op.drop_column('documents', 'parse_result')
    op.drop_column('documents', 'parse_level_reached')
    op.drop_column('documents', 'status')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'original_filename')
    op.drop_column('documents', 'user_id')
    # ### end Alembic commands ###
